name: Lint and build on PR

on: [pull_request]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1

    - name: Install npm packages
      shell: bash
      run: |
        npm install

    - name: Run linter
      shell: bash
      run: |
        npm run lint

    - name: Build app
      shell: bash
      run: |
        npm run build